name: qwen_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.11.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - build==1.3.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - chromadb==1.3.3
      - click==8.3.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - durationpy==0.10
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - google-auth==2.42.1
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kubernetes==34.1.0
      - langchain==1.0.3
      - langchain-core==1.0.3
      - langgraph==1.0.2
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.2
      - langgraph-sdk==0.2.9
      - langsmith==0.4.41
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - packaging==25.0
      - pillow==12.0.0
      - posthog==5.4.0
      - protobuf==6.33.0
      - psutil==7.1.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: C:\Users\hoeve\anaconda3\envs\qwen_env
